// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6-VEkWVDu9HE9fhVbGuvdYmtkIkNbewY',
    appId: '1:76464064668:web:5f91fe2a5c04a96e610559',
    messagingSenderId: '76464064668',
    projectId: 'school-manager-aeaf5',
    authDomain: 'school-manager-aeaf5.firebaseapp.com',
    storageBucket: 'school-manager-aeaf5.firebasestorage.app',
    measurementId: 'G-YJTP6ME879',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnlOEeVEma9zWJiLZoCITjITDCffHBAQ0',
    appId: '1:76464064668:android:14c282b004d5da10610559',
    messagingSenderId: '76464064668',
    projectId: 'school-manager-aeaf5',
    storageBucket: 'school-manager-aeaf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1NztrYTMmEpLgzlCTN0PhtzS8U87Z1k',
    appId: '1:76464064668:ios:f4aea3686cf4c39e610559',
    messagingSenderId: '76464064668',
    projectId: 'school-manager-aeaf5',
    storageBucket: 'school-manager-aeaf5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1NztrYTMmEpLgzlCTN0PhtzS8U87Z1k',
    appId: '1:76464064668:ios:f4aea3686cf4c39e610559',
    messagingSenderId: '76464064668',
    projectId: 'school-manager-aeaf5',
    storageBucket: 'school-manager-aeaf5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6-VEkWVDu9HE9fhVbGuvdYmtkIkNbewY',
    appId: '1:76464064668:web:3df1be0134033975610559',
    messagingSenderId: '76464064668',
    projectId: 'school-manager-aeaf5',
    authDomain: 'school-manager-aeaf5.firebaseapp.com',
    storageBucket: 'school-manager-aeaf5.firebasestorage.app',
    measurementId: 'G-XJM96JDPVY',
  );
}
